version: '2'
services:
   mysql:
    restart: always
    image: mysql:5.7.16
    container_name: my_mysql
    volumes:
      - ./mydir:/mydir
      - ./datadir:/var/lib/mysql
      - ./conf/my.cnf:/etc/my.cnf
      -  ~/root/docker:/docker-entrypoint-initdb.d
    environment:
      - "MYSQL_ROOT_PASSWORD=123456"
      - "MYSQL_DATABASE=mydb"
      - "TZ=Asia/Shanghai"
    ports:
      - 3307:3306


   eid-service:
    container_name: salary-service
    restart: always
    image: salary-service:latest
    volumes:
      #- /salary-service.jar:/salary-service.jar
      - /etc/localtime:/etc/localtime
    ports:
      - "80:8081"
    environment:
      - TZ="Asia/Shanghai"
    build:
      context: .
      dockerfile: Dockerfile
    command: ['java','-jar','salary-service.jar']